language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  global:
    secure: G7oslMLR89rhHId6PvFwuQM7lmZBJ0VGbpJ2eeI67fNxBFh6ZnhhYcMcxKPlfNFUkeelmQLLptn/GxLkXXT/vuABdlpvQtNcTCo76LKAsMJrao/rufA1qOKVC6Vc9DKaXVfJBRX95aUKLCC7HkHYkt8ryPCkSZZ0/B/SXA+nvm0=

before_script:
  - mvn javadoc:javadoc

# Publish javadoc to http://zk-1931.github.io/javazab/javadoc
after_success:
  - .utility/push-javadoc-to-gh-pages.sh
