language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  global:
    secure: X49it0ImkmAwo1X1gX4H22xQfa8pwTKxpjvvIFI21Deif17VEpaIn0QB1cZ4PyAqv44Y7sXbMIiUrq53Lge5TqgigvNM6KjQsvDr6r+6kPhPwfLHS90V0GRkNF49sMpq68J88rbwMqM44l2fpR4Ke0KBjWraqIQ8XgAdAKnCP/o=

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install protobuf-compiler
  # Install packages needed for document generation.
  - sudo apt-get install nodejs
  - sudo gem install bundler

before_script:
  - .utility/before_script.sh

script:
  - .utility/build.sh

# Publish javadoc to http://zk1931.github.io/jzab
after_success:
  - .utility/publish-artifacts.sh

after_failure:
  - cat target/surefire-reports/*output.txt
